[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci', 'npm --prefix server ci']

[phases.build]
cmds = ['npm run build', 'npm --prefix server run railway:build']

[start]
cmd = 'npm --prefix server run railway:start'
